// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Ttelo.Server.DataAccess;

namespace Ttelo.Server.Migrations
{
    [DbContext(typeof(TteloContext))]
    [Migration("20180604161843_AddDeltaToMatch")]
    partial class AddDeltaToMatch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ttelo.Shared.Model.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Delta");

                    b.Property<int?>("LoserPlayerId");

                    b.Property<DateTime>("Time");

                    b.Property<int?>("WinnerPlayerId");

                    b.HasKey("MatchId");

                    b.HasIndex("LoserPlayerId");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Ttelo.Shared.Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Ttelo.Shared.Model.Match", b =>
                {
                    b.HasOne("Ttelo.Shared.Model.Player", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserPlayerId");

                    b.HasOne("Ttelo.Shared.Model.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
